version: '2'
services:
    web:
        image: nginx:alpine
        container_name: web
        volumes:
            - /www/laravel-shop:/var/www/html
            - ./etc/site:/etc/nginx/conf.d
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log/:/var/log/dnmp
        ports:
            - "80:80"
            - "443:443"
        restart: always
    php:
        build: 
            context: ./etc/php
            args: 
                PHP_VERSION: latest
        container_name: php
        restart: always
        environment:
            LANG: C.UTF-8
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "/www/laravel-shop:/var/www/html"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: myadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: dean
            MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
            MYSQL_DATABASE: laravel_shop
        volumes:
            - ./data/db/mysql:/var/lib/mysql
            - ./etc/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        restart: always
        volumes:
            - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
            - ./data/db/redis/:/data/:rw
        command: redis-server /usr/local/etc/redis/redis.conf
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "8025:8025"
            - "1025:1025"
        restart: always
    es:
        build:
          context: ./etc/elasticsearch
        container_name: es
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        restart: always
        volumes:
            - ./data/db/es:/usr/share/elasticsearch/data
        ports:
            - 9200:9200