version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - ${WORKSPACE_DIR}:/var/www/html
            - ./etc/site:/etc/nginx/conf.d
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log/:/var/log/dnmp
        ports:
            - "80:80"
            - "443:443"
        restart: always
    php:
        build: 
            context: ./etc/php
            args: 
                PHP_VERSION: ${PHP_VERSION}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "${WORKSPACE_DIR}:/var/www/html"
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql:${MYSQL_VERSION}
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - ./etc/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf