version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - ${WORKSPACE_DIR}:/var/www/html
            - ./etc/site:/etc/nginx/conf.d
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log/:/var/log/dnmp
        ports:
            - "80:80"
            - "443:443"
        restart: always
    php:
        build: 
            context: ./etc/php
            args: 
                PHP_VERSION: ${PHP_VERSION}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "${WORKSPACE_DIR}:/var/www/html"
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql:${MYSQL_VERSION}
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - ./etc/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    redis:
        image: redis:${REDIS_VERSION}
        ports:
            - "6379:6379"
        restart: always
        volumes:
            - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
            - ./data/db/redis/:/data/:rw
        command: redis-server /usr/local/etc/redis/redis.conf
    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
            - "1025:1025"
        restart: always
    elasticsearch:
        build:
            context: ./etc/elasticsearch
            args: 
                ES_VERSION: ${ELASTICSEARCH_VERSION}
        ports:
            - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - ./data/db/elasticsearch:/usr/share/elasticsearch/data